#!/usr/bin/env bash

set -e
set -u

### configuration ##############################################################

: ${KONG_ADMIN_URL:="https://127.0.0.1:8443/fadmin"}
: ${KONG_ADMIN_SECRET:="UOwOLA464wLHXIWh0p8vY1SfXsX3t25j"}
: ${GATEWAY_URL:="http://gateway:8080"}

### requests ###################################################################

# services

curl -i -k -X PUT \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/gateway" \
  --data "url=$GATEWAY_URL"

# routes

curl -i -k -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/gateway/routes" \
  --data "paths[]=/function&paths[]=/async-function" \
  --data "protocols[]=http" \
  --data "methods[]=POST" \
  --data "strip_path=false"

# plugins

curl -i -k -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/gateway/plugins" \
  --data "name=key-auth" \
  --data "config.hide_credentials=true" \
  --data "config.key_names=apikey"

curl -i -k -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/gateway/plugins" \
  --data "name=acl" \
  --data "config.whitelist=betausers"

curl -i -k -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/gateway/plugins" \
  --data "name=rate-limiting" \
  --data "config.minute=5"
