#!/usr/bin/env bash

set -e
set -u

### configuration ##############################################################

: ${KONG_ADMIN_URL:="https://fops.raas.dev/fadmin"}
: ${KONG_ADMIN_SECRET:="jO6i96fbtLXsFLXKTWUVgNk6N2M3Hnl8"}

### requests ###################################################################

# fops

curl -i -X PUT \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/demo"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/demo/acls" \
  --data "group=fops"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/demo/basic-auth" \
  --data "username=demo" \
  --data "password=hyJq2@9c6v2P"

# faas

curl -i -X PUT \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/guest"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/guest/acls" \
  --data "group=faas"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/consumers/guest/key-auth"
