#!/usr/bin/env bash

set -e
set -u

### configuration ##############################################################

: ${KONG_ADMIN_URL:="https://fops.raas.dev/fadmin"}
: ${KONG_ADMIN_SECRET:=""}
: ${ALERTMANAGER_URL:="http://alertmanager.openfaas.svc.cluster.local:9093"}

### requests ###################################################################

# services

curl -i -X PUT \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/alerts" \
  --data "url=$ALERTMANAGER_URL"

# routes

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/alerts/routes" \
  --data "hosts[]=alerts.raas.dev" \
  --data "protocols[]=http"

# plugins

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/alerts/plugins" \
  --data "name=basic-auth" \
  --data "config.hide_credentials=true"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/alerts/plugins" \
  --data "name=acl" \
  --data "config.whitelist=fops"
