#!/usr/bin/env bash

set -e
set -u

### configuration ##############################################################

: ${KONG_ADMIN_URL:="https://fops.raas.dev/fadmin"}
: ${KONG_ADMIN_SECRET:=""}
: ${GATEWAY_URL:="http://gateway.openfaas.svc.cluster.local:8080"}

### requests ###################################################################

# services

curl -i -X PUT \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/faas" \
  --data "url=$GATEWAY_URL"

# routes

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/faas/routes" \
  --data "hosts[]=raas.dev&paths[]=/function&paths[]=/async-function" \
  --data "protocols[]=http" \
  --data "methods[]=POST" \
  --data "strip_path=false"

# plugins

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/faas/plugins" \
  --data "name=key-auth" \
  --data "config.hide_credentials=true" \
  --data "config.key_names=apikey"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/faas/plugins" \
  --data "name=acl" \
  --data "config.whitelist=faas"

curl -i -X POST \
  --header "apikey: $KONG_ADMIN_SECRET" \
  --url "$KONG_ADMIN_URL/services/faas/plugins" \
  --data "name=rate-limiting" \
  --data "config.minute=5"
