version: "3.3"


services:
  nodered:
    image: registry.raas.dev/asyrjasalo/node-red:0.20.7
    ports:
      - 1880:1880
    volumes:
      - nodered-data:/data
    networks:
      - iot


networks:
  iot:
    driver: overlay
    attachable: true


volumes:
  nodered-data:
